[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
hex = "0.4.3"
bitcoin = "0.32.5"
candid = "0.10.13"
ic-cdk = "0.18.5"
serde = "1.0.132"
serde_bytes = "0.11.15"
leb128 = "0.2.5"
# getrandom = { version = "0.2.15", features = ["custom"] }
